### ISSUE TITLE
ID没有更换

### ISSUE THREAD

**Issue by chenshen03** [binbibi/XTeamLView#1]
按照README的说法，将两个文件放置到Teamviewer的目录下。启动后ID还是未变，请问下这是为什么哈？

**Comment by binbibi** [comment]
你可以下载 https://download.sysinternals.com/files/DebugView.zip,看下log,然后上传log,我怀疑是dll没注入或者是hook失败

**Comment by chenshen03** [comment]
已解决了，使用管理员权限打开XTvClient后，ID就变换了。谢谢~
